server.port=12500
spring.application.name=fortune-demo
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fortune}
spring.datasource.username=${DB_USERNAME:fortune}
spring.datasource.password=${DB_PASSWORD:fortune}
spring.sql.init.mode=always
